change report path

diff --git a/.github/workflows/code-scan-dojo.yaml b/.github/workflows/code-scan-dojo.yaml
--- a/.github/workflows/code-scan-dojo.yaml
+++ b/.github/workflows/code-scan-dojo.yaml
@@ -49,14 +49,17 @@ jobs:
             if [ -z ${{inputs.SCAN_EXCLUDE}} ]; then export arg="";  else export arg="--skip-files ${{inputs.SCAN_EXCLUDE}}"; fi
             if [ "${{inputs.SCAN_INCLUDE}}" = "." ]; then export SCAN_INCLUDE="/";  else export SCAN_INCLUDE="${{inputs.SCAN_INCLUDE}}"; fi            
             brakeman -A -q -f sonar -p . --only-files  "${SCAN_INCLUDE}" -o external_report --no-exit-on-warn --no-exit-on-error ${arg}
-    
-    - name: Ruby rubocop scan
-      if: contains(inputs.SCAN_TYPE, 'Ruby')
-      continue-on-error: true
-      run: |
-            gem install rubocop
-            rubocop  --format json --out rubocop.json --fail-level fatal || true
-            echo "RUBOCOP_REPORT=rubocop.json" >> $GITHUB_ENV
+            echo "SCAN_TYPE_DOJO=$(echo 'Brakeman Scan')" >> $GITHUB_ENV
+            ls -lart external_report
+
+    # Doesn't support by dojo
+    # - name: Ruby rubocop scan
+    #   if: contains(inputs.SCAN_TYPE, 'Ruby')
+    #   continue-on-error: true
+    #   run: |
+    #         gem install rubocop
+    #         rubocop  --format json --out rubocop.json --fail-level fatal || true
+    #         echo "RUBOCOP_REPORT=rubocop.json" >> $GITHUB_ENV
             
                    
     - name: IaC KICS scan
@@ -65,19 +68,20 @@ jobs:
         if [ -z ${{inputs.SCAN_EXCLUDE}} ]; then export arg="";  else export arg="--exclude-paths ${{inputs.SCAN_EXCLUDE}}"; fi
         docker run -w /path -v $PWD:/path checkmarx/kics scan -o /path -p "${{inputs.SCAN_INCLUDE}}" --report-formats "json" --ignore-on-exit "all" ${arg} 
         ls -lart
+        mv results.json external_report
         echo "SCAN_TYPE_DOJO=$(echo 'KICS Scan')" >> $GITHUB_ENV
 
-
-    - name: Nodejs scan
-      if: contains(inputs.SCAN_TYPE, 'JavaScript')
-      uses: ajinabraham/njsscan-action@master
-      with:
-        args: '. --sonarqube  --output njsscan_report.sonar || true'
+    # Doesn't support by dojo
+    # - name: Nodejs scan
+    #   if: contains(inputs.SCAN_TYPE, 'JavaScript')
+    #   uses: ajinabraham/njsscan-action@master
+    #   with:
+    #     args: '. --sonarqube  --output njsscan_report.sonar || true'
         
-    - name: process njsscan report
-      if: contains(inputs.SCAN_TYPE, 'JavaScript')
-      run: |
-        awk 'BEGIN{ FS=OFS=": " } /\"endColumn\"/{ match($NF, /^[0-9]+/); $NF=($NF-1) substr($NF, RLENGTH+1) }1' njsscan_report.sonar > external_report
+    # - name: process njsscan report
+    #   if: contains(inputs.SCAN_TYPE, 'JavaScript')
+    #   run: |
+    #     awk 'BEGIN{ FS=OFS=": " } /\"endColumn\"/{ match($NF, /^[0-9]+/); $NF=($NF-1) substr($NF, RLENGTH+1) }1' njsscan_report.sonar > external_report
 
 
     - name: Prepare dojo ENV
@@ -100,7 +104,7 @@ jobs:
         
         [scan]
         scan_type = ${{ env.SCAN_TYPE_DOJO }}
-        file_path = results.json
+        file_path = external_report/results.json
         EOF
 
     - name: Get Scripts
